### PR TITLE
Catalyst + CMake

### PR DESCRIPTION
**Pull request by rupertnash**
This work contain’s some uncommitted work in the repo Steven sent us.

I have re-done the CMake in a more modern style (since I couldn’t make it work) and stripped out all the unused, commented out code. I hope this is useful.

Plus a few minor tidy ups I spotted.

### CODE REVIEW

**Comment by rupertnash** [comment]
@steven-chien - any chance you could have a look at this and consider merging? This would be handy for VESTEC and getting things consistently installed. Thanks!

**Comment by rupertnash** [comment]
@steven-chien: I just noticed that you have made some changes to the CMake in master, which where straightforward I have repeated on my branch (see last 2 commits).

Regarding the larger diff in 0b94ac9 which changes the site specific stuff:
I think most CMake users would consider site-specific config like that an anti-pattern.

One solution is cmake presets (https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) which is quite new (cmake 3.19) and so you might have to install your own cmake for a while until systems catch up.

A half-way solution might be to create a cache variable say `SITE` which you then use to include a cmake file holding this stuff, perhaps in `cmake/sites/${SITE}.cmake`?

**Comment by steven-chien** [comment]
Hi @rupertnash, thank you for all the contributions. The site-specific settings were there to quickly fix for the students who need to use it in a course on Beskow. Ideally, we should have something like preset to provide portability but as you said it is quite new (I just check, the latest on Beskow is CMake 3.18). I guess the site cache for inclusion is the way to go.

**Comment by rupertnash** [comment]
OK - I will implement the top level site stuff but leave filling in the details to you, if that's alright?

**Comment by steven-chien** [comment]
yes please do, thank you for that!

**Comment by rupertnash** [comment]
OK - I think if you put your stuff in say `cmake/sites/beskow.cmake` this will work. Any problems reply here and I'll help.

**Pull request merged**
